### ISSUE TITLE
Problems with proguard on Android release build

### ISSUE THREAD

**Issue by MR-Neto** [iyegoroff/react-native-image-filter-kit#24]
Hi! 

I am using version 0.4.14 on my React Native app, which runs on RN version 0.59.8. More specifically, I using the component `OverlayBlendColor`. 

I followed all installation steps and the package is working properly on iOS (both development and production versions) and on Android development. However, I can't make it work for Android on a production environment. 

Does any one has any insights?

Thanks!

**Comment by iyegoroff** [comment]
Hi @MR-Neto , does your app crash due to rnifk or you can't see the expected output image?

**Comment by MR-Neto** [comment]
I can't see the expected output

A quarta, 2/10/2019, 20:08, iyegoroff <notifications@github.com> escreveu:

**Comment by iyegoroff** [comment]
Probably you have to use latest rnifk version with rn ">=0.60.0", because there were several fixes after 0.4.14 related to Android filters.

**Comment by MR-Neto** [comment]
I am updated my app to the latest RN version (0.61.2) and rnifk to version 0.5.18, and I am getting this error when rnifk is compiled in JAVA. @iyegoroff any ideas? thanks

`C:\Users\Miguel Neto\Desktop\niikiis-apps\node_modules\react-native-image-filter-kit\android\src\main\java\iyegoroff\imagefilterkit\MainReactPackageWithFrescoCache.java:61: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\Miguel Neto\Desktop\niikiis-apps\node_modules\react-native-image-filter-kit\android\src\main\java\iyegoroff\imagefilterkit\MainReactPackageWithFrescoCache.java:63: error: cannot find symbol
    List<ModuleSpec> modules = super.getNativeModules(context);
                                    ^
  symbol: method getNativeModules(ReactApplicationContext)
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-filter-kit:compileDebugJavaWithJavac'.`

**Comment by iyegoroff** [comment]
If you aren't importing MainReactPackageWithFrescoCache directly in your code, I guess it is ok to just delete that method for now.

**Comment by MR-Neto** [comment]
I deleted the method and it is compiling. However, the package was still not working on Android Production. I found that the problem was with my release configuration. The package doesn't work with proguard. I had to comment the following lines from `android\app\build.gradle`.

```
release {
            //minifyEnabled 
            //shrinkResources true
            //enableProguardInReleaseBuilds
            //proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            ....
        }
```

cd

**Comment by iyegoroff** [comment]
rn v0.61.x is now supported by rnifk v0.6.0

However, I don't know how to resolve that proguard issue. If you manage to handle it, please share your workaround here.

**Comment by jphilipstevens** [comment]
I've run into an issue with the release build as well. I see this stack trace:
2020-04-07 08:32:41.887 25039-25039/? W/System.err: java.lang.NoSuchFieldException: No field mControllerListener in class Lcom/facebook/react/views/image/f; (declaration of 'com.facebook.react.views.image.f' appears in base.apk)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at iyegoroff.reflectutils.a.a(ReflectUtils.java:11)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at iyegoroff.reflectutils.a.a(ReflectUtils.java:10)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at iyegoroff.reflectutils.a.a(ReflectUtils.java:9)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at iyegoroff.imagefilterkit.t1.a(ReactImageViewUtils.java:1)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at iyegoroff.imagefilterkit.m1.a(ImageFilter.java:59)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at iyegoroff.imagefilterkit.m1.c(ImageFilter.java:1)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at iyegoroff.imagefilterkit.m1.onLayout(ImageFilter.java:3)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.view.View.layout(View.java:22466)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6304)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.uimanager.k.a(NativeViewHierarchyManager.java:39)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.uimanager.k.a(NativeViewHierarchyManager.java:30)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.uimanager.s0$u.execute(UIViewOperationQueue.java:2)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.uimanager.s0$a.run(UIViewOperationQueue.java:10)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.uimanager.s0.i(UIViewOperationQueue.java:11)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.uimanager.s0.i(UIViewOperationQueue.java:1)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.uimanager.s0$i.b(UIViewOperationQueue.java:6)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.uimanager.c.a(GuardedFrameCallback.java:1)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.modules.core.e$d.a(ReactChoreographer.java:7)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.facebook.react.modules.core.a$a$a.doFrame(ChoreographerCompat.java:1)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:791)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:722)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-04-07 08:32:41.888 25039-25039/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)


I'm testing out removing proguard since we have had past issues with proguard unintentionally removing libs.

Updating the file with the following lines did not help but may be needed for others:

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /Users/ide/Library/Android/sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:
# This fixed a crash elsewhere with SVG files
-keep public class com.horcrux.svg.** {*;}

# Render Script may be removed by PG
-keep class android.support.v8.renderscript.** { *; }
-keep class androidx.renderscript.** { *; }

one idea I may test is keeping ALL classes in facebook packages. once I test I will let you know
