### ISSUE TITLE
FrescoBackgroundExecutor java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/renderscript/Allocation$MipmapControl

### ISSUE THREAD

**Issue by ngocluan1192** [iyegoroff/react-native-image-filter-kit#34]
Please give me some advice to fix this issue on Android. Thank you so much.

RN 0.61.5
compileSdkVersion 29
buildToolsVersion 29

```
2020-03-27 01:48:50.455 4415-4759/com.purple.mcat E/AndroidRuntime: FATAL EXCEPTION: FrescoBackgroundExecutor-4
    Process: com.purple.mcat, PID: 4415
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/renderscript/Allocation$MipmapControl;
        at iyegoroff.imagefilterkit.utility.RenderscriptSingularPostProcessor$RenderscriptContext.<init>(RenderscriptSingularPostProcessor.java:23)
        at iyegoroff.imagefilterkit.nativeplatform.scriptintrinsic.ScriptIntrinsicConvolve3x3PostProcessor.processSingularRenderscript(ScriptIntrinsicConvolve3x3PostProcessor.java:51)
        at iyegoroff.imagefilterkit.utility.RenderscriptSingularPostProcessor.process(RenderscriptSingularPostProcessor.java:70)
        at com.facebook.imagepipeline.request.BasePostprocessor.process(BasePostprocessor.java:61)
        at iyegoroff.imagefilterkit.utility.MultiPostProcessor.process(MultiPostProcessor.java:68)
        at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.postprocessInternal(PostprocessorProducer.java:247)
        at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.doPostprocessing(PostprocessorProducer.java:217)
        at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.access$600(PostprocessorProducer.java:73)
        at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer$2.run(PostprocessorProducer.java:175)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.renderscript.Allocation$MipmapControl" on path: DexPathList[[zip file "/data/app/com.purple.mcat-mRgMzYb9n7II2q0pcCWMJQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.purple.mcat-mRgMzYb9n7II2q0pcCWMJQ==/lib/x86, /data/app/com.purple.mcat-mRgMzYb9n7II2q0pcCWMJQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at iyegoroff.imagefilterkit.utility.RenderscriptSingularPostProcessor$RenderscriptContext.<init>(RenderscriptSingularPostProcessor.java:23) 
        at iyegoroff.imagefilterkit.nativeplatform.scriptintrinsic.ScriptIntrinsicConvolve3x3PostProcessor.processSingularRenderscript(ScriptIntrinsicConvolve3x3PostProcessor.java:51) 
        at iyegoroff.imagefilterkit.utility.RenderscriptSingularPostProcessor.process(RenderscriptSingularPostProcessor.java:70) 
        at com.facebook.imagepipeline.request.BasePostprocessor.process(BasePostprocessor.java:61) 
        at iyegoroff.imagefilterkit.utility.MultiPostProcessor.process(MultiPostProcessor.java:68) 
        at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.postprocessInternal(PostprocessorProducer.java:247) 
        at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.doPostprocessing(PostprocessorProducer.java:217) 
        at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.access$600(PostprocessorProducer.java:73) 
        at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer$2.run(PostprocessorProducer.java:175) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51) 
        at java.lang.Thread.run(Thread.java:764) 

```

**Comment by iyegoroff** [comment]
What is your rnifk version?

**Comment by yairopro** [comment]
Hi @iyegoroff 
I have the same problem.
Maybe I can answer.
What's RNIFK ?

```
react: 16.13.1
react-native: 0.62.2
react-native-image-filter-kit: 0.7.1
```

**Comment by iyegoroff** [comment]
Hi @yairopro 
rnifk is react-native-image-filter-kit. 
Your versions look OK, so I'm not sure what causing this error.

**Comment by yairopro** [comment]
I've followed the instructions. The library is well installed.
I even started to use some filters like _1977_, _Aden_, _Brannan_, _Brooklyn_, etc.
They work nice. 
_**Thanks a lot** for this library by the way._

The error happens only when I try to use some specific filters like _Gingham_ or _Hudson_.

**Comment by iyegoroff** [comment]
> The error happens only when I try to use some specific filters like Gingham or Hudson.

This means that renderscript was not configured properly.

Maybe you need just to clean the project `cd android && ./gradlew clean` before building.

**Comment by yairopro** [comment]
Even after a clean, it's still crashing when using those filters.

**Comment by iyegoroff** [comment]
Please check if you got the same error when running [CustomNativeFilter](https://github.com/iyegoroff/react-native-image-filter-kit/tree/master/examples/CustomNativeFilter) example.

**Comment by yairopro** [comment]
The demo works perfectly on the device. 

![image](https://user-images.githubusercontent.com/8110568/85946716-19862c80-b94f-11ea-9a0c-598aa0e59bb5.png)

**Comment by iyegoroff** [comment]
This means that something in your android/gradle project configuration conflicts with rnifk.

**Comment by yairopro** [comment]
I'll check.

**Comment by s123121** [comment]
I have the same problem. 
I am not well-versed with android so I could not debug much (and the demo with perfectly). So unfortunately, I have to switch to gl-react
